# Generated by Django 3.0.5 on 2020-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200418_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.CharField(default='img.jpg', max_length=20, unique=True),
        ),
    ]
