# Generated by Django 3.0.5 on 2020-04-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
