# Generated by Django 3.0.5 on 2020-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200428_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ready',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
