# Generated by Django 3.0.5 on 2020-05-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
